name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-verion: 8.0.x

    - name: Build
      run: dotnet build src/AsyncLinqR.sln --configuration Release
    
    - name: Test
      run: dotnet test src/AsyncLinqR.Tests