name: Publish NuGet pacakge

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Up .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build package
      run: dotnet pack ./AsyncLinqR/AsyncLinqR.csproj -c Release --output ../packages /P:Version=${{ github.event.release.tag_name }}
      working-directory: ./src

    - name: Push package to NuGet.org
      run: dotnet nuget push ./packages/AsyncLinqR${{ github.event.release.tag_name }}.nupkg --api-key ${{ secrets.NUGET_PACKAGES }} --source https://api.nuget.org/v3/index.json